### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by petuhovskiy** [rwlist/opscript#1]
- [x] It works
- [x] It doesn't crash on while true
- [ ] It doesn't crash on large allocations
- [ ] print and println don't spam in stdout
- [ ] stdlib usage allowed
- [ ] message/user/chat info can be accessed
- [ ] arbitrary logic for message replying
- [ ] builtin package can be more useful
- [ ] Code and some other state persisted in db
- [ ] KV can be used to store data
- [ ] Daily lottery bot (aka SublimeBot) can be implemented
- [ ] Code from other namespaces can be reused
- [ ] Code can be imported from github
- [ ] It's pretty good
